import type { Metadata } from "next";
import "./globals.css";
import "react-photo-view/dist/react-photo-view.css";
import { Toaster } from "@/components/ui/sonner";
import { Header } from "@/components/app/header/Header";
import { geistMono, geistSans, nanumMyeongjo, poiretOne } from "@/lib/fonts";
import { AuthProvider } from "@/lib/providers/AuthProvider";
import { getCurrentUser } from "@/lib/auth";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getCurrentUser();
  return (
    <html lang="en">
      <AuthProvider initialUser={user}>
        <body
          className={`${geistMono.variable} ${geistSans.variable} ${poiretOne.variable} ${nanumMyeongjo.variable} antialiased text-site-text bg-site-background`}
        >
          <Header />
          <main className="font-body">{children}</main>
          <Toaster position="top-right" richColors />
        </body>
      </AuthProvider>
    </html>
  );
}
