import type { Metadata } from "next";
import "./globals.css";
import "react-photo-view/dist/react-photo-view.css";
import { Toaster } from "@/components/ui/sonner";
import { Header } from "@/components/app/header/Header";
import { allura, nanumMyeongjo } from "@/lib/fonts";
import { AuthProvider } from "@/lib/providers/AuthProvider";
import { getCurrentUser } from "@/lib/auth";
import { Footer } from "@/components/app/home/footer/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getCurrentUser();
  return (
    <html lang="en">
      <AuthProvider initialUser={user}>
        <body
          className={`${nanumMyeongjo.variable} ${allura.variable} antialiased text-site-text bg-site-background flex flex-col min-h-dvh`}
        >
          <Header />
          <main className="font-body grow flex flex-col">{children}</main>
          <Footer />
          <Toaster position="top-right" richColors />
        </body>
      </AuthProvider>
    </html>
  );
}
